<br><br>

## **Import necessary Python libraries and modules**

First, we will import necessary Python libraries and modules. These include as `gdown`, for downloading large files from Google Drive (where we will get our UCSD Goodreads reviews), as well as scikit-learn (`sklearn`) and PyTorch (`torch`), for various machine learning tools.

In [6]:

# For data manipulation and analysis
import pandas as pd
import numpy as np

# For machine learning tools and evaluation
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report


# For deep learning
# https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html
import torch
#import transformers
from sklearn.metrics import confusion_matrix

To use the HuggingFace [`transformers` Python library](https://huggingface.co/transformers/installation.html), we will install it with `pip`.

In [ ]:
!pip install transformers

In [2]:
from transformers import XLMRobertaForSequenceClassification, XLMRobertaTokenizerFast
from transformers import Trainer, TrainingArguments

<br><br>

## **Set parameters and file paths**

In [7]:

model_name = 'xlm-roberta-base'  

# This is the name of the program management system for NVIDIA GPUs. We're going to send our code here.
device_name = 'cuda'       

# This is the maximum number of tokens in any document sent to BERT.
max_length = 128                                                        

# This is the name of the directory where we'll save our model. You can name it whatever you want.

cached_model_directory_name = 'Polarity_fin_xlmr'  

In [5]:
#stiamo utlizzando la GPU?
import torch

# If there's a GPU available...
if torch.cuda.is_available():    

    # Tell PyTorch to use the GPU.    
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla K80


In [3]:
#train=pd.read_csv("train_def_pol.csv")
train=pd.read_csv("C:\\Users\\Fossati\\Desktop\\Tesi\\Dati\\Dati_FineTuningBERT\\Train_Test_polarity\\def_Data\\train_def_pol.csv")
train

Unnamed: 0                                           Sentence  \
0               0  It provides a great insight into the behind th...   
1               1  A girl and her boyfriend decide to take that s...   
2               2  The children's novel "keys of the Kingdom Mist...   
3               3  Monday and his creepy butler, who leave him wi...   
4               4  There he discovers a world beautifully ripe wi...   
...           ...                                                ...   
11835       11835  보는내내 엉엉울엇네요 스토리가 쪼금 허술한? 면도있지만 안내상씨 연기 너무좋았어요♥...   
11836       11836             저스틴 채트원하고 에미 로섬이 대체 저런 영화 왜 찍었는지 모르겠다.   
11837       11837                                        부셔버리고 싶다...   
11838       11838  Arthur Penhaligon은 곧 죽을 것입니다. 미스터 먼데이와 그의 집사 S...   
11839       11839                                                줫 망   

      Polarity_Classification  
0                      Neutra  
1                      Neutra  
2                      Neutra  
3                    Negativa  
4                      Neutra  
...                       ...  
11835                Positiva  
11836                Negativa  
11837                Negativa  
11838                  Neutra  
11839                Negativa  

[11840 rows x 3 columns]

In [4]:

test=pd.read_csv("C:\\Users\\Fossati\\Desktop\\Tesi\\Dati\\Dati_FineTuningBERT\\Train_Test_polarity\\def_Data\\test_def_pol.csv")
test

Unnamed: 0                                           Sentence  \
0              0  This is one of the books that my dad read out ...   
1              1  Garth Nix's 'Mister Monday' was a highly cleve...   
2              2  Includes affirmations, visualizations, and pra...   
3              3                                 Monday was fantasy   
4              4  Weird and dangerous creatures are hunting him ...   
...          ...                                                ...   
1387        1387  달리는 동안 그는 이것을 작은 열쇠라고 하는 것을 갖게 되었고, 그것은 일종의 시계...   
1388        1388  아벨라 부터 들어간 기아 순정 이긴 한데 프라이드 는 잘 모르 겠 네요 ㅋㅋ 끝물 ...   
1389        1389                                         이전이나 변함없다.   
1390        1390                                      [3점] 뭐 하자는거지?   
1391        1391                                          진부해서 재미없다   

     Polarity_Classification  
0                   Positiva  
1                   Positiva  
2                   Positiva  
3                     Neutra  
4                     Neutra  
...                      ...  
1387                  Neutra  
1388                  Neutra  
1389                Negativa  
1390                Negativa  
1391                Negativa  

[1392 rows x 3 columns]

In [5]:
#creiamo le liste di train e test. 1.8k train 250 test  
train_texts=train['Sentence']
train_labels=train['Polarity_Classification']
test_texts=test['Sentence']
test_labels=test['Polarity_Classification']


<br><br>

## **Split the data into training and test sets**

In [11]:
len(train_texts), len(train_labels), len(test_texts), len(test_labels)

(11840, 11840, 1392, 1392)

Here's an example of a training label and review:

In [12]:
train_labels[0], train_texts[0]

('Neutra',
 'It provides a great insight into the behind the scenes goings-on in parliament, the rivalries and treacheries in the run up to Winston Churchill becoming Britains war time Prime Minister')

<br><br>

## **Encode data for BERT**

We're going to transform our texts and labels into a format that BERT (via Huggingface and PyTorch) will understand. This is called *encoding* the data.

Here are the steps we need to follow:

1. The labels&mdash;in this case, Goodreads genres&mdash;need to be turned into integers rather than strings.

2. The texts&mdash;in this case, Goodreads reviews&mdash;need to be truncated if they're more than 512 tokens or padded if they're fewer than 512 tokens. The tokens, or words in the texts, also need to be separated into "word pieces" and matched to their embedding vectors.

3. We need to add special tokens to help BERT:

| BERT special token | Explanation |
| --------------| ---------|
| [CLS] | Start token of every document. |
| [SEP] | Separator between each sentence |
| [PAD] | Padding at the end of the document as many times as necessary, up to 512 tokens |
|  &#35;&#35; | Start of a "word piece" |




In [13]:
tokenizer = XLMRobertaTokenizerFast.from_pretrained(model_name) # The model_name needs to match our pre-trained model.

Downloading:   0%|          | 0.00/4.83M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/8.68M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/615 [00:00<?, ?B/s]

Here we will create a map of our labels, or Goodreads genres, to integer keys. We take the unique labels, and then we make a dictionary that associates each label/tag with an integer.

**Note:** HuggingFace documentation sometimes refers to "labels" as "tags" but these are the same thing. We use "labels" throughout this notebook for clarity.

In [14]:
#unique_labels = set(label for label in train_labels)
#label2id = {label: id for id, label in enumerate(unique_labels)}
#id2label = {id: label for label, id in label2id.items()}

In [15]:
unique_labels={'Neutra', 'Positiva', 'Negativa'}
label2id={'Negativa': 2, 'Neutra': 0, 'Positiva': 1}
id2label={2:'Negativa', 0:'Neutra', 1:'Positiva'}

In [16]:
unique_labels

{'Negativa', 'Neutra', 'Positiva'}

In [17]:
label2id.keys()

dict_keys(['Negativa', 'Neutra', 'Positiva'])

In [18]:
id2label.keys()

dict_keys([2, 0, 1])

Now let's encode our texts and labels!

In [19]:
train_encodings = tokenizer(train_texts.tolist(), truncation=True, padding=True, max_length=max_length)
test_encodings  = tokenizer(test_texts.tolist(), truncation=True, padding=True, max_length=max_length)

train_labels_encoded = [label2id[y] for y in train_labels.tolist()]
test_labels_encoded  = [label2id[y] for y in test_labels.tolist()]

**Examine a Goodreads review in the training set after encoding**

In [20]:
' '.join(train_encodings[29].tokens[0:100])

'<s> ▁" ▁The ▁war time ▁episode s , ▁however , ▁are ▁less ▁satisfac tory </s> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad>'

**Examine a Goodreads review in the test set after encoding**

In [21]:
' '.join(test_encodings[0].tokens[0:100])

'<s> ▁This ▁is ▁one ▁of ▁the ▁books ▁that ▁my ▁dad ▁read ▁out ▁lo ud ▁to ▁me ▁at ▁bed time , ▁but ▁whenever ▁he ▁had ▁to ▁put ▁it ▁down , ▁I ▁begge d ▁him ▁to ▁read ▁more </s> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad>'

**Examine the training labels after encoding**

In [22]:
set(train_labels_encoded)

{0, 1, 2}

**Examine the test labels after encoding**

In [23]:
set(test_labels_encoded)

{0, 1, 2}

<br><br>

## **Make a custom Torch dataset**

Here we combine the encoded labels and texts into dataset objects. We use the custom Torch `MyDataSet` class to make a `train_dataset` object from  the `train_encodings` and `train_labels_encoded`. We also make a `test_dataset` object from `test_encodings`, and `test_labels_encoded`.

In [24]:
class MyDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

In [25]:
train_dataset = MyDataset(train_encodings, train_labels_encoded)
test_dataset = MyDataset(test_encodings, test_labels_encoded)

In [26]:
' '.join(train_dataset.encodings[0].tokens[0:100])

'<s> ▁It ▁provides ▁a ▁great ▁insight ▁into ▁the ▁behind ▁the ▁scene s ▁going s - on ▁in ▁par li ament , ▁the ▁rival ries ▁and ▁tre ache ries ▁in ▁the ▁run ▁up ▁to ▁Winston ▁Churchill ▁becoming ▁Britain s ▁war ▁time ▁Prime ▁Minister </s> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad>'

In [27]:
' '.join(test_dataset.encodings[1].tokens[0:100])

"<s> ▁Gar th ▁Ni x ' s ▁' M ister ▁Monday ' ▁was ▁a ▁highly ▁c lever , ▁creative , ▁and ▁entertain ing ▁read ▁that ▁had ▁me ▁up ▁into ▁the ▁we e ▁hours ▁of ▁the ▁morning ▁following ▁Arthur ' s ▁adventure s ▁in ▁the ▁House </s> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad>"

<br><br>

## **Load pre-trained BERT model**

In [28]:
# The model_name needs to match the name used for the tokenizer above.
model = XLMRobertaForSequenceClassification.from_pretrained(model_name, num_labels=len(id2label)).to(device_name)

Downloading:   0%|          | 0.00/1.04G [00:00<?, ?B/s]

Some weights of the model checkpoint at xlm-roberta-base were not used when initializing XLMRobertaForSequenceClassification: ['lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.dense.weight', 'roberta.pooler.dense.weight', 'lm_head.dense.bias', 'roberta.pooler.dense.bias', 'lm_head.decoder.weight', 'lm_head.layer_norm.bias']
- This IS expected if you are initializing XLMRobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.dense

<br><br>

## **Set the BERT fine-tuning parameters**

These are the arguments we'll set in the HuggingFace TrainingArguments objects, which we'll then pass to the HuggingFace Trainer object. There are many more possible arguments, but here we highlight the basics and some common gotchas.

When training your own model, you should search over these parameters to find the best settings for your particular dataset. You should use a held-out set of validation data for this step.

| Parameter | Explanation |
|-----------| ------------|
| num_train_epochs | total number of training epochs (how many times to pass through the entire dataset; too much can cause overfitting) |
| per_device_train_batch_size | batch size per device during training |
| per_device_eval_batch_size |  batch size for evaluation |
|  warmup_steps |  number of warmup steps for learning rate scheduler (set lower because of small dataset size) |
| weight_decay | strength of weight decay (reduces size of weights, like regularization) |
| output_dir | output directory for the fine-tuned model and configuration files |
| logging_dir | directory for storing logs |
| logging_steps | how often to print logging output (so that we can stop training early if the loss isn't going down) |
| evaluation_strategy | evaluate while training so that we can see the accuracy going up |

In [29]:
training_args=TrainingArguments(
    num_train_epochs=4,              # total number of training epochs
    per_device_train_batch_size=16,  # batch size per device during training
    per_device_eval_batch_size=16,   # batch size for evaluation
    learning_rate=2e-5,              # initial learning rate for Adam optimizer
    warmup_steps=100,                # number of warmup steps for learning rate scheduler (set lower because of small dataset size)
    weight_decay=0.01,               # strength of weight decay
    output_dir='./results',          # output directory
    logging_dir='./logs',            # directory for storing logs
    logging_steps=2000,               # number of steps to output logging (set lower because of small dataset size)
    evaluation_strategy='steps',     # evaluate during fine-tuning so that we can see progress
    save_strategy='no'
)

<br><br>

## **Fine-tune the BERT model**

First, we define a custom evaluation function that returns the accuracy. You could modify this function to return precision, recall, F1, and/or other metrics.

In [30]:
def compute_metrics(pred):
  labels = pred.label_ids
  preds = pred.predictions.argmax(-1)
  acc = accuracy_score(labels, preds)
  return {
      'accuracy': acc,
  }

Then we create a HuggingFace `Trainer` object using the `TrainingArguments` object that we created above. We also send our `compute_metrics` function to the `Trainer` object, along with our test and train datasets.

**Note:** This is what we've been aiming for this whole time! All the work of tokenizing, creating datasets, and setting the training arguments was for this cell.

In [31]:
trainer = Trainer(
    model=model,                         # the instantiated 🤗 Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=train_dataset,         # training dataset
    eval_dataset=test_dataset,           # evaluation dataset (usually a validation set; here we just send our test set)
    compute_metrics=compute_metrics      # our custom evaluation function 
)

Time to finally fine-tune! 

Be patient; if you've set everything in Colab to use GPUs, then it should only take a minute or two to run, but if you're running on CPU, it can take hours.

After every 10 steps (as we specified in the TrainingArguments object), the trainer will output the current state of the model, including the training loss, validation ("test") loss, and accuracy (from our `compute_metrics` function).

You should see the loss going down and the accuracy going up. If instead they are staying the same or oscillating, you probably need to change the fine-tuning parameters.

In [32]:
trainer.train()                                                                                         

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
***** Running training *****
  Num examples = 11840
  Num Epochs = 4
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 2960


***** Running Evaluation *****
  Num examples = 1392
  Batch size = 16


Training completed. Do not forget to share your model on huggingface.co/models =)




TrainOutput(global_step=2960, training_loss=0.45682241078969593, metrics={'train_runtime': 2502.6603, 'train_samples_per_second': 18.924, 'train_steps_per_second': 1.183, 'total_flos': 3115262865899520.0, 'train_loss': 0.45682241078969593, 'epoch': 4.0})

In [ ]:
#tempo di training: 4 ore

<br><br>

## **Save fine-tuned model**

The following cell will save the model and its configuration files to a directory in Colab. To preserve this model for future use, you should download the model to your computer.

In [33]:
trainer.save_model(cached_model_directory_name)

Saving model checkpoint to Polarity_fin_xlmr
Configuration saved in Polarity_fin_xlmr/config.json
Model weights saved in Polarity_fin_xlmr/pytorch_model.bin


(Optional) If you've already fine-tuned and saved the model, you can reload it using the following line. You don't have to run fine-tuning every time you want to evaluate.

<br><br>

## **Evaluate fine-tuned model**

The following function of the `Trainer` object will run the built-in evaluation, including our `compute_metrics` function.

In [34]:
trainer.evaluate() 

***** Running Evaluation *****
  Num examples = 1392
  Batch size = 16


{'epoch': 4.0,
 'eval_accuracy': 0.9267241379310345,
 'eval_loss': 0.25862929224967957,
 'eval_runtime': 21.6901,
 'eval_samples_per_second': 64.177,
 'eval_steps_per_second': 4.011}

But we might want to do more fine-grained analysis of the model, so we extract the predicted labels.

In [35]:
predicted_results = trainer.predict(test_dataset)

***** Running Prediction *****
  Num examples = 1392
  Batch size = 16


In [36]:
predicted_results.predictions.shape

(1392, 3)

In [37]:
predicted_labels = predicted_results.predictions.argmax(-1) # Get the highest probability prediction
predicted_labels = predicted_labels.flatten().tolist()      # Flatten the predictions into a 1D list
predicted_labels = [id2label[l] for l in predicted_labels]  # Convert from integers back to strings for readability

In [38]:
len(predicted_labels)

1392

In [39]:
print(classification_report(test_labels, 
                            predicted_labels))     

              precision    recall  f1-score   support

    Negativa       0.93      0.92      0.92       460
      Neutra       0.96      0.92      0.94       467
    Positiva       0.90      0.94      0.92       465

    accuracy                           0.93      1392
   macro avg       0.93      0.93      0.93      1392
weighted avg       0.93      0.93      0.93      1392



In [ ]:
#la novità è che c'è risultato generale sufficientemente buoni per tutte e 5 classi

In [ ]:
#RELOAD THE MODEL

In [ ]:
#valutazione per domain

In [12]:
def prediction_test(dataset):  #dataset fa riferimento al set di dati che vogliamo passare, modello dipende dal tipo di FT
#poi ci sarà anche la funzione per predire senza labels
    tok = XLMRobertaTokenizerFast.from_pretrained('xlm-roberta-base')
    modello=XLMRobertaForSequenceClassification.from_pretrained(cached_model_directory_name)
    test_texts=dataset['Sentence']
    test_labels=dataset['Polarity_Classification']

    unique_labels={'Neutra', 'Positiva', 'Negativa'}
    label2id={'Negativa': 2, 'Neutra': 0, 'Positiva': 1}
    id2label={2:'Negativa', 0:'Neutra', 1:'Positiva'}
    
#train_encodings = tok(train_texts.tolist(), truncation=True, padding=True, max_length=max_length)
    test_encodings  = tok(test_texts.tolist(), truncation=True, padding=True, max_length=max_length)

#train_labels_encoded = [label2id[y] for y in train_labels.tolist()]
    test_labels_encoded  = [label2id[y] for y in test_labels.tolist()]
    

    class MyDataset(torch.utils.data.Dataset):
        def __init__(self, encodings, labels):
            self.encodings = encodings
            self.labels = labels

        def __getitem__(self, idx):
            item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
            item['labels'] = torch.tensor(self.labels[idx])
            return item

        def __len__(self):
            return len(self.labels)

#train_dataset = MyDataset(train_encodings, train_labels_encoded)
    test_dataset = MyDataset(test_encodings, test_labels_encoded)
    
    training_args = TrainingArguments(
    num_train_epochs=4,              # total number of training epochs
    per_device_train_batch_size=16,  # batch size per device during training
    per_device_eval_batch_size=16,   # batch size for evaluation
    learning_rate=2e-5,              # initial learning rate for Adam optimizer
    warmup_steps=100,                # number of warmup steps for learning rate scheduler (set lower because of small dataset size)
    weight_decay=0.01,               # strength of weight decay
    output_dir='./results',          # output directory
    logging_dir='./logs',            # directory for storing logs
    logging_steps=2000,               # number of steps to output logging (set lower because of small dataset size)
    evaluation_strategy='steps'     # evaluate during fine-tuning so that we can see progress
)
    
    trainer = Trainer(model=modello, args=training_args)  #basta avere il modello come parametro

    predicted_results=trainer.predict(test_dataset)
    
    predicted_labels = predicted_results.predictions.argmax(-1) # Get the highest probability prediction
    predicted_labels = predicted_labels.flatten().tolist()      # Flatten the predictions into a 1D list
    predicted_labels = [id2label[l] for l in predicted_labels]  # Convert from integers back to strings for readability

#len(predicted_labels)

    return print(classification_report(test_labels,predicted_labels)), print(confusion_matrix(test_labels,predicted_labels,labels=['Positiva','Neutra','Negativa']))

In [14]:
prediction_test(test)   #tabella per tutto il test

loading file https://huggingface.co/xlm-roberta-base/resolve/main/sentencepiece.bpe.model from cache at C:\Users\Fossati/.cache\huggingface\transformers\9df9ae4442348b73950203b63d1b8ed2d18eba68921872aee0c3a9d05b9673c6.00628a9eeb8baf4080d44a0abe9fe8057893de20c7cb6e6423cddbf452f7d4d8
loading file https://huggingface.co/xlm-roberta-base/resolve/main/tokenizer.json from cache at C:\Users\Fossati/.cache\huggingface\transformers\daeda8d936162ca65fe6dd158ecce1d8cb56c17d89b78ab86be1558eaef1d76a.a984cf52fc87644bd4a2165f1e07e0ac880272c1e82d648b4674907056912bd7
loading file https://huggingface.co/xlm-roberta-base/resolve/main/added_tokens.json from cache at None
loading file https://huggingface.co/xlm-roberta-base/resolve/main/special_tokens_map.json from cache at None
loading file https://huggingface.co/xlm-roberta-base/resolve/main/tokenizer_config.json from cache at None
loading configuration file https://huggingface.co/xlm-roberta-base/resolve/main/config.json from cache at C:\Users\Fossati/.

              precision    recall  f1-score   support

    Negativa       0.92      0.91      0.91       460
      Neutra       0.96      0.92      0.94       467
    Positiva       0.89      0.93      0.91       465

    accuracy                           0.92      1392
   macro avg       0.92      0.92      0.92      1392
weighted avg       0.92      0.92      0.92      1392

[[432   9  24]
 [ 24 429  14]
 [ 31  10 419]]


(None, None)

In [ ]:
#come è normale che sia gli errori neg/neu vanno più verso la classificazione positiva, essendo maggiori i dati per positiva nel train
#le positive sbagliate vanno più verso le negative che verso le neutre
#lo stesso vale per le negative, 'a causa' del coreano, come si evince meglio sotto




In [ ]:
#la confusion matrix si legge: riga1: positiva, riga2: neutra, riga3: negativa

In [15]:
prediction_test(test[:205])   #tabella per inglesi   

loading file https://huggingface.co/xlm-roberta-base/resolve/main/sentencepiece.bpe.model from cache at C:\Users\Fossati/.cache\huggingface\transformers\9df9ae4442348b73950203b63d1b8ed2d18eba68921872aee0c3a9d05b9673c6.00628a9eeb8baf4080d44a0abe9fe8057893de20c7cb6e6423cddbf452f7d4d8
loading file https://huggingface.co/xlm-roberta-base/resolve/main/tokenizer.json from cache at C:\Users\Fossati/.cache\huggingface\transformers\daeda8d936162ca65fe6dd158ecce1d8cb56c17d89b78ab86be1558eaef1d76a.a984cf52fc87644bd4a2165f1e07e0ac880272c1e82d648b4674907056912bd7
loading file https://huggingface.co/xlm-roberta-base/resolve/main/added_tokens.json from cache at None
loading file https://huggingface.co/xlm-roberta-base/resolve/main/special_tokens_map.json from cache at None
loading file https://huggingface.co/xlm-roberta-base/resolve/main/tokenizer_config.json from cache at None
loading configuration file https://huggingface.co/xlm-roberta-base/resolve/main/config.json from cache at C:\Users\Fossati/.

              precision    recall  f1-score   support

    Negativa       0.92      0.92      0.92        26
      Neutra       0.98      0.91      0.94        90
    Positiva       0.93      0.99      0.96        89

    accuracy                           0.95       205
   macro avg       0.94      0.94      0.94       205
weighted avg       0.95      0.95      0.95       205

[[88  1  0]
 [ 6 82  2]
 [ 1  1 24]]


(None, None)

In [41]:
#per en le neutre errate vanno più verso il positivo, a causa del fatto che nel train EN sono più le positive

In [16]:
prediction_test(test[205:699])    #it

loading file https://huggingface.co/xlm-roberta-base/resolve/main/sentencepiece.bpe.model from cache at C:\Users\Fossati/.cache\huggingface\transformers\9df9ae4442348b73950203b63d1b8ed2d18eba68921872aee0c3a9d05b9673c6.00628a9eeb8baf4080d44a0abe9fe8057893de20c7cb6e6423cddbf452f7d4d8
loading file https://huggingface.co/xlm-roberta-base/resolve/main/tokenizer.json from cache at C:\Users\Fossati/.cache\huggingface\transformers\daeda8d936162ca65fe6dd158ecce1d8cb56c17d89b78ab86be1558eaef1d76a.a984cf52fc87644bd4a2165f1e07e0ac880272c1e82d648b4674907056912bd7
loading file https://huggingface.co/xlm-roberta-base/resolve/main/added_tokens.json from cache at None
loading file https://huggingface.co/xlm-roberta-base/resolve/main/special_tokens_map.json from cache at None
loading file https://huggingface.co/xlm-roberta-base/resolve/main/tokenizer_config.json from cache at None
loading configuration file https://huggingface.co/xlm-roberta-base/resolve/main/config.json from cache at C:\Users\Fossati/.

              precision    recall  f1-score   support

    Negativa       0.89      0.92      0.90       124
      Neutra       0.92      0.88      0.90       204
    Positiva       0.90      0.93      0.91       166

    accuracy                           0.90       494
   macro avg       0.90      0.91      0.91       494
weighted avg       0.91      0.90      0.90       494

[[154   8   4]
 [ 15 179  10]
 [  3   7 114]]


(None, None)

In [42]:
#per it gli errori di classificazione di pos e neg tendono ad andare più verso le neutre, il che è un bene
#le neutre errate vanno più verso il positivo

In [17]:
prediction_test(test[699:])   #tabella per koreane    


loading file https://huggingface.co/xlm-roberta-base/resolve/main/sentencepiece.bpe.model from cache at C:\Users\Fossati/.cache\huggingface\transformers\9df9ae4442348b73950203b63d1b8ed2d18eba68921872aee0c3a9d05b9673c6.00628a9eeb8baf4080d44a0abe9fe8057893de20c7cb6e6423cddbf452f7d4d8
loading file https://huggingface.co/xlm-roberta-base/resolve/main/tokenizer.json from cache at C:\Users\Fossati/.cache\huggingface\transformers\daeda8d936162ca65fe6dd158ecce1d8cb56c17d89b78ab86be1558eaef1d76a.a984cf52fc87644bd4a2165f1e07e0ac880272c1e82d648b4674907056912bd7
loading file https://huggingface.co/xlm-roberta-base/resolve/main/added_tokens.json from cache at None
loading file https://huggingface.co/xlm-roberta-base/resolve/main/special_tokens_map.json from cache at None
loading file https://huggingface.co/xlm-roberta-base/resolve/main/tokenizer_config.json from cache at None
loading configuration file https://huggingface.co/xlm-roberta-base/resolve/main/config.json from cache at C:\Users\Fossati/.

              precision    recall  f1-score   support

    Negativa       0.93      0.91      0.92       310
      Neutra       0.99      0.97      0.98       173
    Positiva       0.86      0.90      0.88       210

    accuracy                           0.92       693
   macro avg       0.93      0.93      0.93       693
weighted avg       0.92      0.92      0.92       693

[[190   0  20]
 [  3 168   2]
 [ 27   2 281]]


(None, None)

In [43]:
#le positive sbagliate vengono classificate come negative per ko, nonostante il bilanciamento nel train per le classi
#lo stesso vale per le negative
#per KO apprende bene per le neutre, tuttavia in caso di errore pos/neg non vengono 'considerate'