<br><br>

## **Import necessary Python libraries and modules**

In [14]:

# For data manipulation and analysis
import pandas as pd
import numpy as np

# For machine learning tools and evaluation
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report


# For deep learning
# https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html
import torch
#import transformers
from sklearn.metrics import confusion_matrix


To use the HuggingFace [`transformers` Python library](https://huggingface.co/transformers/installation.html), we will install it with `pip`.

In [2]:
!pip install transformers

     |████████████████████████████████| 3.8 MB 5.2 MB/s 
     |████████████████████████████████| 6.5 MB 9.1 MB/s 
     |████████████████████████████████| 895 kB 35.4 MB/s 
     |████████████████████████████████| 596 kB 28.9 MB/s 
     |████████████████████████████████| 67 kB 4.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


Once `transformers` is installed, we will import modules for `DistilBert`, a *distilled* or smaller version of a BERT model that runs more quickly and uses less computing power. This makes it ideal for those just getting started with BERT.

In [15]:
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification
from transformers import Trainer, TrainingArguments

<br><br>

## **Set parameters and file paths**

In [16]:
# This is the name of the BERT model that we want to use. 
# We're using DistilBERT to save space (it's a distilled version of the full BERT model), 
# and we're going to use the cased (vs uncased) version.
model_name = 'distilbert-base-multilingual-cased'  

# This is the name of the program management system for NVIDIA GPUs. We're going to send our code here.
device_name = 'cuda'       

# This is the maximum number of tokens in any document sent to BERT.
max_length = 128                                                       

# This is the name of the directory where we'll save our model. You can name it whatever you want.
#cached_model_directory_name = 'ABSA_FineTuning_BERT'  
cached_model_directory_name = 'Emotions_fin_mbert'  

In [5]:
#stiamo utlizzando la GPU?
import torch

# If there's a GPU available...
if torch.cuda.is_available():    

    # Tell PyTorch to use the GPU.    
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla K80


In [17]:
train=pd.read_csv("C:\\Users\\Fossati\\Desktop\\Tesi\\Dati\\Dati_FineTuningBERT\\Train_Test_emotion\\Strategy_fin\\train_def.csv")
train

Unnamed: 0  level_0                                           Sentence  \
0               0    39939  i have to admit that i feel a little irate as ...   
1               1    27439                     [NAME] are the liars, we know.   
2               2    30643         $42,000 fine over a JOKE is unreasonable.    
3               3    45392  i have that feeling but idol anime is pretty p...   
4               4     8480  > To say NDP foreign policy consistently suppo...   
...           ...      ...                                                ...   
80662       80662    73600                             최고의 영화. 다시 나타날 수 없는 작품   
80663       80663    46112                                   청춘이네 보는 내내 두근거렸다   
80664       80664    97318                 2시간짜리반전캠페인영화. 나에게서 캐산의 추억을 앗아갔다...   
80665       80665    83289  아 넘 질질 끌어요속 터져 못보겠습니다 빠른 전계 부탁드려요 드라마 사설이 넘길어 ...   
80666       80666     5728                       딱 C급 공포미스터리. 해외서도 보니 비디오직행인듯   

       Emotions  
0         Anger  
1         Anger  
2         Anger  
3           Joy  
4       Neutral  
...         ...  
80662   Sadness  
80663      Fear  
80664  Surprise  
80665   Sadness  
80666     Anger  

[80667 rows x 4 columns]

In [18]:
test=pd.read_csv("C:\\Users\\Fossati\\Desktop\\Tesi\\Dati\\Dati_FineTuningBERT\\Train_Test_emotion\\Strategy_fin\\test_def.csv")
test

Unnamed: 0  level_0                                           Sentence  \
0              0    33476  This does not sound like a good situation for ...   
1              1    11870  There's really no way to know since my lady ho...   
2              2    34327  Considering that cheating is a mark of high-st...   
3              3    50190  i am feeling a little apprehensive but i m sur...   
4              4    49266  i still feel like there are more than enough t...   
...          ...      ...                                                ...   
9484        9484    92647  멋있을 수도 있는 게 하나도 안 멋있고, 감동적일 수도 있는 장면에 아무런 감동도 ...   
9485        9485    92038                                  배우가 너무 아깝다고 생각했다.   
9486        9486    65497  음 기왕 일산 까지 보신 다면 렉서스 의 suv 하브 모델 은 어떠하실 지요 . R...   
9487        9487    45413                          발연기. 득보잡 배우들. 장르는 저예산 에로.   
9488        9488    67241  현대 씨 썰 베라크루즈 엔진 입니 다 주로 낚시 배 나 중소 형 어선 에 쓰입니 다...   

      Emotions  
0        Anger  
1      Neutral  
2        Anger  
3         Fear  
4          Joy  
...        ...  
9484  Surprise  
9485  Surprise  
9486   Neutral  
9487      Fear  
9488   Neutral  

[9489 rows x 4 columns]

In [19]:
#creiamo le liste di train e test. 1.8k train 250 test  
train_texts=train['Sentence']
train_labels=train['Emotions']
test_texts=test['Sentence']
test_labels=test['Emotions']


<br><br>

## **Split the data into training and test sets**

In [11]:
len(train_texts), len(train_labels), len(test_texts), len(test_labels)

(80667, 80667, 9489, 9489)

Here's an example of a training label and review:

In [12]:
train_labels[0], train_texts[0]

('Anger',
 'i have to admit that i feel a little irate as well but its under control')

<br><br>

## **Encode data for BERT**

We're going to transform our texts and labels into a format that BERT (via Huggingface and PyTorch) will understand. This is called *encoding* the data.

Here are the steps we need to follow:

1. The labels&mdash;in this case, Goodreads genres&mdash;need to be turned into integers rather than strings.

2. The texts&mdash;in this case, Goodreads reviews&mdash;need to be truncated if they're more than 512 tokens or padded if they're fewer than 512 tokens. The tokens, or words in the texts, also need to be separated into "word pieces" and matched to their embedding vectors.

3. We need to add special tokens to help BERT:

| BERT special token | Explanation |
| --------------| ---------|
| [CLS] | Start token of every document. |
| [SEP] | Separator between each sentence |
| [PAD] | Padding at the end of the document as many times as necessary, up to 512 tokens |
|  &#35;&#35; | Start of a "word piece" |




Here we will load `DistilBertTokenizerFast` from the HuggingFace library, which will do all the work of encoding the texts for us. The `tokenizer()` will break word tokens into word pieces, truncate to 512 tokens, and add padding and special BERT tokens.

In [13]:
tokenizer = DistilBertTokenizerFast.from_pretrained(model_name) # The model_name needs to match our pre-trained model.

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/972k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.87M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466 [00:00<?, ?B/s]

Here we will create a map of our labels, or Goodreads genres, to integer keys. We take the unique labels, and then we make a dictionary that associates each label/tag with an integer.

**Note:** HuggingFace documentation sometimes refers to "labels" as "tags" but these are the same thing. We use "labels" throughout this notebook for clarity.

In [14]:
#unique_labels = set(label for label in train_labels)
#label2id = {label: id for id, label in enumerate(unique_labels)}
#id2label = {id: label for label, id in label2id.items()}

In [15]:
unique_labels={'Sadness', 'Surprise', 'Joy', 'Neutral', 'Anger','Fear'}
label2id={'Sadness':0, 'Surprise':1, 'Joy':2, 'Neutral':3, 'Anger':4, 'Fear':5}
id2label={ 0:'Sadness', 1:'Surprise', 2:'Joy', 3:'Neutral', 4:'Anger', 5:'Fear'} 

In [16]:
unique_labels

{'Anger', 'Fear', 'Joy', 'Neutral', 'Sadness', 'Surprise'}

In [17]:
label2id.keys()

dict_keys(['Sadness', 'Surprise', 'Joy', 'Neutral', 'Anger', 'Fear'])

In [18]:
id2label.keys()

dict_keys([0, 1, 2, 3, 4, 5])

Now let's encode our texts and labels!

In [19]:
train_encodings = tokenizer(train_texts.tolist(), truncation=True, padding=True, max_length=max_length)
test_encodings  = tokenizer(test_texts.tolist(), truncation=True, padding=True, max_length=max_length)

train_labels_encoded = [label2id[y] for y in train_labels.tolist()]
test_labels_encoded  = [label2id[y] for y in test_labels.tolist()]

In [20]:
' '.join(train_encodings[29].tokens[0:100])

"[CLS] Got it ! I wasn ' t aware that it was a sl ##ur , and thought that it was just a general term used . Thank ##s for the info . [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]"

In [21]:
' '.join(test_encodings[0].tokens[0:100])

'[CLS] This does not sound like a good situation for a child at all im ##o . [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]'

In [22]:
set(train_labels_encoded)

{0, 1, 2, 3, 4, 5}

In [23]:
set(test_labels_encoded)

{0, 1, 2, 3, 4, 5}

<br><br>

## **Make a custom Torch dataset**

Here we combine the encoded labels and texts into dataset objects. We use the custom Torch `MyDataSet` class to make a `train_dataset` object from  the `train_encodings` and `train_labels_encoded`. We also make a `test_dataset` object from `test_encodings`, and `test_labels_encoded`.

In [24]:
class MyDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

In [25]:
train_dataset = MyDataset(train_encodings, train_labels_encoded)
test_dataset = MyDataset(test_encodings, test_labels_encoded)

In [26]:
' '.join(train_dataset.encodings[0].tokens[0:100])

'[CLS] i have to ad ##mit that i feel a little ira ##te as well but its under control [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]'

In [27]:
' '.join(test_dataset.encodings[1].tokens[0:100])

"[CLS] There ' s really no way to know since my lady hormone ##s prevent me from remember ##ing sexual assault ##ers ' ide ##nti ##ties . [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]"

<br><br>

## **Load pre-trained BERT model**

Here we load a pre-trained DistilBERT model and send it to CUDA.

**Note:** If you decide to repeat fine-tuning after already running the following cells, make sure that you re-run this cell to re-load the original pre-trained model before fine-tuning again.

In [28]:
# The model_name needs to match the name used for the tokenizer above.
model = DistilBertForSequenceClassification.from_pretrained(model_name, num_labels=len(id2label)).to(device_name)

Downloading:   0%|          | 0.00/517M [00:01<?, ?B/s]

Some weights of the model checkpoint at distilbert-base-multilingual-cased were not used when initializing DistilBertForSequenceClassification: ['vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_projector.bias', 'vocab_projector.weight', 'vocab_transform.weight', 'vocab_transform.bias']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['pre_classifier.bias', 'classifie

<br><br>

## **Set the BERT fine-tuning parameters**

These are the arguments we'll set in the HuggingFace TrainingArguments objects, which we'll then pass to the HuggingFace Trainer object. There are many more possible arguments, but here we highlight the basics and some common gotchas.

When training your own model, you should search over these parameters to find the best settings for your particular dataset. You should use a held-out set of validation data for this step.

| Parameter | Explanation |
|-----------| ------------|
| num_train_epochs | total number of training epochs (how many times to pass through the entire dataset; too much can cause overfitting) |
| per_device_train_batch_size | batch size per device during training |
| per_device_eval_batch_size |  batch size for evaluation |
|  warmup_steps |  number of warmup steps for learning rate scheduler (set lower because of small dataset size) |
| weight_decay | strength of weight decay (reduces size of weights, like regularization) |
| output_dir | output directory for the fine-tuned model and configuration files |
| logging_dir | directory for storing logs |
| logging_steps | how often to print logging output (so that we can stop training early if the loss isn't going down) |
| evaluation_strategy | evaluate while training so that we can see the accuracy going up |

In [29]:
training_args=TrainingArguments(
    num_train_epochs=4,              # total number of training epochs
    per_device_train_batch_size=16,  # batch size per device during training
    per_device_eval_batch_size=16,   # batch size for evaluation
    learning_rate=2e-5,              # initial learning rate for Adam optimizer
    warmup_steps=100,                # number of warmup steps for learning rate scheduler (set lower because of small dataset size)
    weight_decay=0.01,               # strength of weight decay
    output_dir='./results',          # output directory
    logging_dir='./logs',            # directory for storing logs
    logging_steps=4000,               # number of steps to output logging (set lower because of small dataset size)
    evaluation_strategy='steps',     # evaluate during fine-tuning so that we can see progress
    save_strategy='no'
)

<br><br>

## **Fine-tune the BERT model**

First, we define a custom evaluation function that returns the accuracy. You could modify this function to return precision, recall, F1, and/or other metrics.

In [30]:
def compute_metrics(pred):
  labels = pred.label_ids
  preds = pred.predictions.argmax(-1)
  acc = accuracy_score(labels, preds)
  return {
      'accuracy': acc,
  }

Then we create a HuggingFace `Trainer` object using the `TrainingArguments` object that we created above. We also send our `compute_metrics` function to the `Trainer` object, along with our test and train datasets.

**Note:** This is what we've been aiming for this whole time! All the work of tokenizing, creating datasets, and setting the training arguments was for this cell.

In [31]:
trainer = Trainer(
    model=model,                         # the instantiated 🤗 Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=train_dataset,         # training dataset
    eval_dataset=test_dataset,           # evaluation dataset (usually a validation set; here we just send our test set)
    compute_metrics=compute_metrics      # our custom evaluation function 
)

Time to finally fine-tune! 

Be patient; if you've set everything in Colab to use GPUs, then it should only take a minute or two to run, but if you're running on CPU, it can take hours.

After every 10 steps (as we specified in the TrainingArguments object), the trainer will output the current state of the model, including the training loss, validation ("test") loss, and accuracy (from our `compute_metrics` function).

You should see the loss going down and the accuracy going up. If instead they are staying the same or oscillating, you probably need to change the fine-tuning parameters.

In [32]:
trainer.train()                                                                                                         

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
***** Running training *****
  Num examples = 80667
  Num Epochs = 4
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 20168


***** Running Evaluation *****
  Num examples = 9489
  Batch size = 16
***** Running Evaluation *****
  Num examples = 9489
  Batch size = 16
***** Running Evaluation *****
  Num examples = 9489
  Batch size = 16
***** Running Evaluation *****
  Num examples = 9489
  Batch size = 16
***** Running Evaluation *****
  Num examples = 9489
  Batch size = 16


Training completed. Do not forget to share your model on huggingface.co/models =)




TrainOutput(global_step=20168, training_loss=0.8062978840593023, metrics={'train_runtime': 8274.1732, 'train_samples_per_second': 38.997, 'train_steps_per_second': 2.437, 'total_flos': 1.0686509907941376e+16, 'train_loss': 0.8062978840593023, 'epoch': 4.0})

In [ ]:
#tempo di training: 2 ore

<br><br>

## **Save fine-tuned model**

The following cell will save the model and its configuration files to a directory in Colab. To preserve this model for future use, you should download the model to your computer.

In [33]:
trainer.save_model(cached_model_directory_name)

Saving model checkpoint to Emotions_fin_mbert
Configuration saved in Emotions_fin_mbert/config.json
Model weights saved in Emotions_fin_mbert/pytorch_model.bin


(Optional) If you've already fine-tuned and saved the model, you can reload it using the following line. You don't have to run fine-tuning every time you want to evaluate.

<br><br>

## **Evaluate fine-tuned model**

The following function of the `Trainer` object will run the built-in evaluation, including our `compute_metrics` function.

In [34]:
trainer.evaluate()

***** Running Evaluation *****
  Num examples = 9489
  Batch size = 16


{'epoch': 4.0,
 'eval_accuracy': 0.8263252186742543,
 'eval_loss': 0.4973554313182831,
 'eval_runtime': 68.9555,
 'eval_samples_per_second': 137.611,
 'eval_steps_per_second': 8.614}

In [41]:
#RELOAD THE MODEL

In [42]:
#valutazione per domain

In [24]:
def prediction_test(dataset):  #dataset fa riferimento al set di dati che vogliamo passare, modello dipende dal tipo di FT
#poi ci sarà anche la funzione per predire senza labels
    tok = DistilBertTokenizerFast.from_pretrained('distilbert-base-multilingual-cased')
    modello=DistilBertForSequenceClassification.from_pretrained(cached_model_directory_name)
    test_texts=dataset['Sentence']
    test_labels=dataset['Emotions']

    #unique_labels = set(label for label in test_labels)
    #label2id = {label: id for id, label in enumerate(unique_labels)}
    #id2label = {id: label for label, id in label2id.items()}
    unique_labels={'Sadness', 'Surprise', 'Joy', 'Neutral', 'Anger','Fear'}
    label2id={'Sadness':0, 'Surprise':1, 'Joy':2, 'Neutral':3, 'Anger':4, 'Fear':5}
    id2label={ 0:'Sadness', 1:'Surprise', 2:'Joy', 3:'Neutral', 4:'Anger', 5:'Fear'}  

#train_encodings = tok(train_texts.tolist(), truncation=True, padding=True, max_length=max_length)
    test_encodings  = tok(test_texts.tolist(), truncation=True, padding=True, max_length=128)

#train_labels_encoded = [label2id[y] for y in train_labels.tolist()]
    test_labels_encoded  = [label2id[y] for y in test_labels.tolist()]
    

    class MyDataset(torch.utils.data.Dataset):
        def __init__(self, encodings, labels):
            self.encodings = encodings
            self.labels = labels

        def __getitem__(self, idx):
            item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
            item['labels'] = torch.tensor(self.labels[idx])
            return item

        def __len__(self):
            return len(self.labels)

#train_dataset = MyDataset(train_encodings, train_labels_encoded)
    test_dataset = MyDataset(test_encodings, test_labels_encoded)
    
    training_args = TrainingArguments(
    num_train_epochs=4,              # total number of training epochs
    per_device_train_batch_size=16,  # batch size per device during training
    per_device_eval_batch_size=16,   # batch size for evaluation
    learning_rate=2e-5,              # initial learning rate for Adam optimizer
    warmup_steps=100,                # number of warmup steps for learning rate scheduler (set lower because of small dataset size)
    weight_decay=0.01,               # strength of weight decay
    output_dir='./results',          # output directory
    logging_dir='./logs',            # directory for storing logs
    logging_steps=1500,               # number of steps to output logging (set lower because of small dataset size)
    evaluation_strategy='steps'     # evaluate during fine-tuning so that we can see progress
)
    
    trainer = Trainer(model=modello, args=training_args)  #basta avere il modello come parametro

    predicted_results=trainer.predict(test_dataset)
    
    predicted_labels = predicted_results.predictions.argmax(-1) # Get the highest probability prediction
    predicted_labels = predicted_labels.flatten().tolist()      # Flatten the predictions into a 1D list
    predicted_labels = [id2label[l] for l in predicted_labels]  # Convert from integers back to strings for readability

#len(predicted_labels)

    return print(classification_report(test_labels,predicted_labels)), print(confusion_matrix(test_labels,predicted_labels,labels=['Sadness', 'Surprise', 'Joy', 'Neutral', 'Anger','Fear']))

In [25]:
prediction_test(test) 

loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/vocab.txt from cache at C:\Users\Fossati/.cache\huggingface\transformers\28e5b750bf4f39cc620367720e105de1501cf36ec4ca7029eba82c1d2cc47caf.6c5b6600e968f4b5e08c86d8891ea99e51537fc2bf251435fb46922e8f7a7b29
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/tokenizer.json from cache at C:\Users\Fossati/.cache\huggingface\transformers\5cbdf121f196be5f1016cb102b197b0c34009e1e658f513515f2eebef9f38093.b33e51591f94f17c238ee9b1fac75b96ff2678cbaed6e108feadb3449d18dc24
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/added_tokens.json from cache at None
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/special_tokens_map.json from cache at None
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/tokenizer_config.json from cache at C:\Users\Fossati/.cache\huggingface\transformers\4708

              precision    recall  f1-score   support

       Anger       0.79      0.79      0.79      1547
        Fear       0.78      0.78      0.78      1497
         Joy       0.78      0.79      0.78      1606
     Neutral       0.88      0.85      0.86      1910
     Sadness       0.82      0.80      0.81      1457
    Surprise       0.74      0.78      0.76      1472

    accuracy                           0.80      9489
   macro avg       0.80      0.80      0.80      9489
weighted avg       0.80      0.80      0.80      9489

[[1162   47   60   29   79   80]
 [  39 1147   76   61   42  107]
 [  66   72 1274   74   44   76]
 [  20  138   56 1616   74    6]
 [  64   68   72   53 1226   64]
 [  64   76  102   12   80 1163]]


(None, None)

In [ ]:
#{'Sadness', 'Surprise', 'Joy', 'Neutral', 'Anger','Fear'}

#queste nell'ordine sono le classi per leggere la confusion matrix

In [ ]:
#sugli errori per sadness , il modello classifica con emozioni negative come anger o fear 
#surprise, tende maggiormente ad essere classificata come fear in caso di errore. ma anche qui non ci sono evidenti pattern
#joy: tendenza a non classificare come anger in caso di errore
#neutral: classificazione surprise in caso di errore
#anger: nessun pattern
#errori Fear classificati maggiormente come joy

In [26]:
prediction_test(test[:2972])   

loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/vocab.txt from cache at C:\Users\Fossati/.cache\huggingface\transformers\28e5b750bf4f39cc620367720e105de1501cf36ec4ca7029eba82c1d2cc47caf.6c5b6600e968f4b5e08c86d8891ea99e51537fc2bf251435fb46922e8f7a7b29
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/tokenizer.json from cache at C:\Users\Fossati/.cache\huggingface\transformers\5cbdf121f196be5f1016cb102b197b0c34009e1e658f513515f2eebef9f38093.b33e51591f94f17c238ee9b1fac75b96ff2678cbaed6e108feadb3449d18dc24
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/added_tokens.json from cache at None
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/special_tokens_map.json from cache at None
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/tokenizer_config.json from cache at C:\Users\Fossati/.cache\huggingface\transformers\4708

              precision    recall  f1-score   support

       Anger       0.87      0.88      0.87       526
        Fear       0.92      0.92      0.92       330
         Joy       0.92      0.89      0.91       552
     Neutral       0.84      0.80      0.82       599
     Sadness       0.94      0.94      0.94       471
    Surprise       0.82      0.88      0.85       494

    accuracy                           0.88      2972
   macro avg       0.88      0.89      0.88      2972
weighted avg       0.88      0.88      0.88      2972

[[441   5   0  10   9   6]
 [  1 437  13  25   8  10]
 [  6  18 494  26   5   3]
 [  7  53  20 480  37   2]
 [ 11  14  10  26 461   4]
 [  5   6   1   7   8 303]]


(None, None)

In [11]:
#per l'inglese ci siamo, otteniamo ottimi risultati

In [ ]:
#{'Sadness', 'Surprise', 'Joy', 'Neutral', 'Anger','Fear'}

#per le prime 3 classi se si sbaglia, si classifica maggiormente come neutro
#neutral tende ad andare verso surprise in caso di errore
#per il resto nessun pattern da evidenziare

In [27]:
prediction_test(test[2972:5981])   

loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/vocab.txt from cache at C:\Users\Fossati/.cache\huggingface\transformers\28e5b750bf4f39cc620367720e105de1501cf36ec4ca7029eba82c1d2cc47caf.6c5b6600e968f4b5e08c86d8891ea99e51537fc2bf251435fb46922e8f7a7b29
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/tokenizer.json from cache at C:\Users\Fossati/.cache\huggingface\transformers\5cbdf121f196be5f1016cb102b197b0c34009e1e658f513515f2eebef9f38093.b33e51591f94f17c238ee9b1fac75b96ff2678cbaed6e108feadb3449d18dc24
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/added_tokens.json from cache at None
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/special_tokens_map.json from cache at None
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/tokenizer_config.json from cache at C:\Users\Fossati/.cache\huggingface\transformers\4708

              precision    recall  f1-score   support

       Anger       0.85      0.87      0.86       537
        Fear       0.91      0.93      0.92       312
         Joy       0.89      0.84      0.86       561
     Neutral       0.78      0.75      0.76       604
     Sadness       0.92      0.89      0.91       499
    Surprise       0.77      0.85      0.81       496

    accuracy                           0.85      3009
   macro avg       0.85      0.85      0.85      3009
weighted avg       0.85      0.85      0.85      3009

[[445   5   3  17  19  10]
 [  9 421  12  36  13   5]
 [  9  17 471  47  12   5]
 [  2  78  35 453  35   1]
 [ 13  16   9  27 466   6]
 [  5   7   0   4   6 290]]


(None, None)

In [ ]:
#{'Sadness', 'Surprise', 'Joy', 'Neutral', 'Anger','Fear'}

#sadness surprise e joy verso neutral in caso di errore, come per en
#neutral tende verso surprise in caso di erorre

#per il resto nessun pattern 

In [28]:
prediction_test(test[5981:])     


loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/vocab.txt from cache at C:\Users\Fossati/.cache\huggingface\transformers\28e5b750bf4f39cc620367720e105de1501cf36ec4ca7029eba82c1d2cc47caf.6c5b6600e968f4b5e08c86d8891ea99e51537fc2bf251435fb46922e8f7a7b29
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/tokenizer.json from cache at C:\Users\Fossati/.cache\huggingface\transformers\5cbdf121f196be5f1016cb102b197b0c34009e1e658f513515f2eebef9f38093.b33e51591f94f17c238ee9b1fac75b96ff2678cbaed6e108feadb3449d18dc24
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/added_tokens.json from cache at None
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/special_tokens_map.json from cache at None
loading file https://huggingface.co/distilbert-base-multilingual-cased/resolve/main/tokenizer_config.json from cache at C:\Users\Fossati/.cache\huggingface\transformers\4708

              precision    recall  f1-score   support

       Anger       0.64      0.62      0.63       484
        Fear       0.67      0.67      0.67       855
         Joy       0.54      0.63      0.58       493
     Neutral       0.99      0.97      0.98       707
     Sadness       0.60      0.57      0.58       487
    Surprise       0.61      0.60      0.61       482

    accuracy                           0.69      3508
   macro avg       0.68      0.67      0.67      3508
weighted avg       0.70      0.69      0.69      3508

[[276  37  57   2  51  64]
 [ 29 289  51   0  21  92]
 [ 51  37 309   1  27  68]
 [ 11   7   1 683   2   3]
 [ 40  38  53   0 299  54]
 [ 54  63 101   1  66 570]]


(None, None)

In [ ]:
#{'Sadness', 'Surprise', 'Joy', 'Neutral', 'Anger','Fear'}

#surprise va verso fear in caso di erroe
#fear va verso joy e viceversa in caso di errore
#in caso di errore non viene di fatto considerata la classificazione neutra come ripiego per KO

In [ ]:
#questo modello è buono per emotion, mBERT sembra competitivo sui nostri dati con XLM-R